"""Typed write and read models exposed by Zett storage boundaries."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .artifacts import (
        AgentArtifactEntity,
        AgentArtifactWrite,
        ArticleArtifactContent,
        ArticleArtifactPatch,
        ArtifactContent,
        ArtifactContentBase,
        ArtifactContentPatch,
        ArtifactCreateContent,
        ArtifactStatus,
        ArtifactTextEdit,
        ArtifactType,
        CardArtifactContent,
        CardArtifactPatch,
        ImageArtifactContent,
        ImageArtifactPatch,
        LatexPdfArtifactContent,
        LatexPdfArtifactCreate,
        LatexPdfArtifactPatch,
        SlidesArtifactContent,
        SlidesArtifactPatch,
        apply_artifact_patch,
    )
    from .assets import (
        SessionAssetCreate,
        SessionAssetEntity,
        SessionAssetType,
        StaticAssetCreate,
        StaticAssetEntity,
    )
    from .cards import (
        CardType,
        normalize_card_type,
    )
    from .channels import (
        Channel,
        ChannelLogin,
        ChannelLoginStart,
        ChannelLoginStatus,
        ChannelPluginInfo,
        ChannelType,
        ChannelUpdate,
    )
    from .common import (
        DataImageUrl,
        HttpUrl,
        ImageUrl,
        JsonValue,
        NonBlankName100,
        NonBlankName200,
        NonBlankName500,
    )
    from .key_value import KeyValueRecord
    from .options import (
        ArtifactListOptions,
        ProviderListOptions,
        SessionAssetListOptions,
        SessionListOptions,
        StaticAssetListOptions,
        TagListOptions,
    )
    from .processes import (
        ProcessHealthReport,
        ProcessHeartbeatIn,
        ProcessHeartbeatRecord,
        ProcessHeartbeatStatus,
        ProcessInstanceHealth,
        ProcessRole,
        ProcessRoleHealth,
        RuntimeChildStatus,
        RuntimeStatus,
        ServerRuntimeState,
        ServerStartResult,
    )
    from .providers import (
        ProviderChoice,
        ProviderConnection,
        ProviderEntity,
        ProviderType,
        ProviderWrite,
    )
    from .scheduled_actions import (
        AGENT_PROMPT_ACTION_KIND,
        AgentPromptAction,
    )
    from .scheduled_tasks import (
        CronSchedule,
        ScheduledTaskAction,
        ScheduledTaskCreate,
        ScheduledTaskEntity,
        ScheduledTaskListOptions,
        ScheduledTaskOverlapPolicy,
        ScheduledTaskRunCreate,
        ScheduledTaskRunEntity,
        ScheduledTaskRunListOptions,
        ScheduledTaskRunStatus,
        ScheduledTaskTrigger,
        ScheduledTaskWrite,
    )
    from .sessions import (
        CODE_TO_SESSION_TYPE,
        SESSION_TYPE_TO_CODE,
        AgentSessionCreate,
        AgentSessionTitleUpdate,
        SessionType,
        session_type_from_code,
    )
    from .tags import (
        ArtifactTagEntity,
        SuggestedTag,
        TagEntity,
        TagTreeEntity,
        TagWrite,
    )
    from .usage_activity import (
        ModelUsageActivitySeries,
        UsageActivityDayRecord,
    )

#: Every re-export and the module that defines it. Importing this package used
#: to import all fourteen schema domains — artifacts, tags, providers, scheduled
#: tasks, and their Pydantic models — for every caller, including `zett status`
#: and `zett stop`, which read one small runtime-state file. A name is imported
#: the first time a caller asks for it.
_EXPORTS = {
    "AGENT_PROMPT_ACTION_KIND": ".scheduled_actions",
    "AgentArtifactEntity": ".artifacts",
    "AgentArtifactWrite": ".artifacts",
    "AgentPromptAction": ".scheduled_actions",
    "AgentSessionCreate": ".sessions",
    "AgentSessionTitleUpdate": ".sessions",
    "ArticleArtifactContent": ".artifacts",
    "ArticleArtifactPatch": ".artifacts",
    "ArtifactContent": ".artifacts",
    "ArtifactContentBase": ".artifacts",
    "ArtifactContentPatch": ".artifacts",
    "ArtifactCreateContent": ".artifacts",
    "ArtifactListOptions": ".options",
    "ArtifactStatus": ".artifacts",
    "ArtifactTagEntity": ".tags",
    "ArtifactTextEdit": ".artifacts",
    "ArtifactType": ".artifacts",
    "CODE_TO_SESSION_TYPE": ".sessions",
    "CardArtifactContent": ".artifacts",
    "CardArtifactPatch": ".artifacts",
    "CardType": ".cards",
    "Channel": ".channels",
    "ChannelLogin": ".channels",
    "ChannelLoginStart": ".channels",
    "ChannelLoginStatus": ".channels",
    "ChannelPluginInfo": ".channels",
    "ChannelType": ".channels",
    "ChannelUpdate": ".channels",
    "CronSchedule": ".scheduled_tasks",
    "DataImageUrl": ".common",
    "HttpUrl": ".common",
    "ImageArtifactContent": ".artifacts",
    "ImageArtifactPatch": ".artifacts",
    "ImageUrl": ".common",
    "JsonValue": ".common",
    "KeyValueRecord": ".key_value",
    "LatexPdfArtifactContent": ".artifacts",
    "LatexPdfArtifactCreate": ".artifacts",
    "LatexPdfArtifactPatch": ".artifacts",
    "ModelUsageActivitySeries": ".usage_activity",
    "NonBlankName100": ".common",
    "NonBlankName200": ".common",
    "NonBlankName500": ".common",
    "ProcessHealthReport": ".processes",
    "ProcessHeartbeatIn": ".processes",
    "ProcessHeartbeatRecord": ".processes",
    "ProcessHeartbeatStatus": ".processes",
    "ProcessInstanceHealth": ".processes",
    "ProcessRole": ".processes",
    "ProcessRoleHealth": ".processes",
    "ProviderChoice": ".providers",
    "ProviderConnection": ".providers",
    "ProviderEntity": ".providers",
    "ProviderListOptions": ".options",
    "ProviderType": ".providers",
    "ProviderWrite": ".providers",
    "RuntimeChildStatus": ".processes",
    "RuntimeStatus": ".processes",
    "SESSION_TYPE_TO_CODE": ".sessions",
    "ScheduledTaskAction": ".scheduled_tasks",
    "ScheduledTaskCreate": ".scheduled_tasks",
    "ScheduledTaskEntity": ".scheduled_tasks",
    "ScheduledTaskListOptions": ".scheduled_tasks",
    "ScheduledTaskOverlapPolicy": ".scheduled_tasks",
    "ScheduledTaskRunCreate": ".scheduled_tasks",
    "ScheduledTaskRunEntity": ".scheduled_tasks",
    "ScheduledTaskRunListOptions": ".scheduled_tasks",
    "ScheduledTaskRunStatus": ".scheduled_tasks",
    "ScheduledTaskTrigger": ".scheduled_tasks",
    "ScheduledTaskWrite": ".scheduled_tasks",
    "ServerRuntimeState": ".processes",
    "ServerStartResult": ".processes",
    "SessionAssetCreate": ".assets",
    "SessionAssetEntity": ".assets",
    "SessionAssetListOptions": ".options",
    "SessionAssetType": ".assets",
    "SessionListOptions": ".options",
    "SessionType": ".sessions",
    "SlidesArtifactContent": ".artifacts",
    "SlidesArtifactPatch": ".artifacts",
    "StaticAssetCreate": ".assets",
    "StaticAssetEntity": ".assets",
    "StaticAssetListOptions": ".options",
    "SuggestedTag": ".tags",
    "TagEntity": ".tags",
    "TagListOptions": ".options",
    "TagTreeEntity": ".tags",
    "TagWrite": ".tags",
    "UsageActivityDayRecord": ".usage_activity",
    "apply_artifact_patch": ".artifacts",
    "normalize_card_type": ".cards",
    "session_type_from_code": ".sessions",
}

#: Sorted so the module reads alphabetically, the way the imports used to.
__all__ = [
    "AGENT_PROMPT_ACTION_KIND",
    "AgentArtifactEntity",
    "AgentArtifactWrite",
    "AgentPromptAction",
    "AgentSessionCreate",
    "AgentSessionTitleUpdate",
    "ArticleArtifactContent",
    "ArticleArtifactPatch",
    "ArtifactContent",
    "ArtifactContentBase",
    "ArtifactContentPatch",
    "ArtifactCreateContent",
    "ArtifactListOptions",
    "ArtifactStatus",
    "ArtifactTagEntity",
    "ArtifactTextEdit",
    "ArtifactType",
    "CODE_TO_SESSION_TYPE",
    "CardArtifactContent",
    "CardArtifactPatch",
    "CardType",
    "Channel",
    "ChannelLogin",
    "ChannelLoginStart",
    "ChannelLoginStatus",
    "ChannelPluginInfo",
    "ChannelType",
    "ChannelUpdate",
    "CronSchedule",
    "DataImageUrl",
    "HttpUrl",
    "ImageArtifactContent",
    "ImageArtifactPatch",
    "ImageUrl",
    "JsonValue",
    "KeyValueRecord",
    "LatexPdfArtifactContent",
    "LatexPdfArtifactCreate",
    "LatexPdfArtifactPatch",
    "ModelUsageActivitySeries",
    "NonBlankName100",
    "NonBlankName200",
    "NonBlankName500",
    "ProcessHealthReport",
    "ProcessHeartbeatIn",
    "ProcessHeartbeatRecord",
    "ProcessHeartbeatStatus",
    "ProcessInstanceHealth",
    "ProcessRole",
    "ProcessRoleHealth",
    "ProviderChoice",
    "ProviderConnection",
    "ProviderEntity",
    "ProviderListOptions",
    "ProviderType",
    "ProviderWrite",
    "RuntimeChildStatus",
    "RuntimeStatus",
    "SESSION_TYPE_TO_CODE",
    "ScheduledTaskAction",
    "ScheduledTaskCreate",
    "ScheduledTaskEntity",
    "ScheduledTaskListOptions",
    "ScheduledTaskOverlapPolicy",
    "ScheduledTaskRunCreate",
    "ScheduledTaskRunEntity",
    "ScheduledTaskRunListOptions",
    "ScheduledTaskRunStatus",
    "ScheduledTaskTrigger",
    "ScheduledTaskWrite",
    "ServerRuntimeState",
    "ServerStartResult",
    "SessionAssetCreate",
    "SessionAssetEntity",
    "SessionAssetListOptions",
    "SessionAssetType",
    "SessionListOptions",
    "SessionType",
    "SlidesArtifactContent",
    "SlidesArtifactPatch",
    "StaticAssetCreate",
    "StaticAssetEntity",
    "StaticAssetListOptions",
    "SuggestedTag",
    "TagEntity",
    "TagListOptions",
    "TagTreeEntity",
    "TagWrite",
    "UsageActivityDayRecord",
    "apply_artifact_patch",
    "normalize_card_type",
    "session_type_from_code",
]


def __getattr__(name: str) -> object:
    """Import one re-exported schema on first access."""
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(importlib.import_module(module_name, __package__), name)
    globals()[name] = value
    return value
